### ISSUE TITLE
NA values to rtnorm

### ISSUE THREAD

**Issue by tmelliott** [chjackson/msm#1]
I noted something about `NA` values in your TODO file, but not specifically for this little quirk.

```{r}
rtnorm(1, NA)
```
runs forever rather than complaining about an `NA`. 

I couldn't work out why my code took all night to run and still made no progress - turns out I was indexing `x[i]` where `i > length(x)`. Ideally `msm` would complain about missing values and exit. 
Cheers!

**Comment by chjackson** [comment]
I think this is now fixed in the latest commit.  Thanks for the first issue report on this new repository!
