### ISSUE TITLE
Observations within subjects ... are not ordered by time

### ISSUE THREAD

**Issue by SPriyanshi-30** [chjackson/msm#100]
Hi, 
I get the following error while calculating crude initial values for transition intensities. I also checked my data frame to make sure that the observations are ordered by id and time. I would appreciate any insights. Thank you!

time: could be 0, 1, 2 (0: baseline, 1: at 1 year, 2: at 2 year)

-  when time=0, diff_year: time in years between baseline and year 1
-  when time=1, diff_year: time in years between year 1 and year 2
-  when time=2, diff_year: time in years between baseline and year 2

state: could be 1,3,4. 4 is the absorbing state. 

All participants have at least 2 observations with max number of observations being 3. This data is from a 2 year randomized control trial. I have also attached a sample dataset. 

[msm_sample.csv](https://github.com/chjackson/msm/files/15175459/msm_sample.csv)

```
#Print transition state
statetable.msm(state, participant_id, data = dat.A)
dat.A$state = as.numeric (as.factor(dat.A$state))

   to
from   1   3   4
    1 200  12   7
    3   0  37  45

# Sort the data frame by participant_id and time
dat.A <- dat.A[order(dat.A$participant_id, dat.A$time), ]

packageVersion("msm") #1.7.1

Q = matrix (0.25, ncol = 3, nrow = 3); Q[3,]=Q[1,3]=0
Q.crude = crudeinits.msm(state~diff_year, participant_id, data = dat.A, qmatrix = Q)

Error in msm.check.times(time, subject, state) : 
  Observations within subjects 1, 3, 18 and others are not ordered by time
```

**Comment by SPriyanshi-30** [comment]
[msm_sample.csv](https://github.com/chjackson/msm/files/15175454/msm_sample.csv)

**Comment by chjackson** [comment]
In `crudeinits.msm()` (and in `msm()`), the `time` variable should be the observation times, not the interval between observations.  So I think you meant `state ~ time`, not `state ~ diff_year`.   The error message was because the observations were not ordered by `diff_year`, which they didn't need to be.

**Comment by SPriyanshi-30** [comment]
You are right. It worked with `state ~ time`. Thank you so much!
