### ISSUE TITLE
Question: CI for transition intensities ratios

### ISSUE THREAD

**Issue by iago-pssjd** [chjackson/msm#103]
Dear Prof. Jackson,

I have found at least a couple of papers where they show ratios of transition intensities with Confidence Intervals. See Table 3 of https://www.neurology.org/doi/10.1212/WNL.0000000000200051 or Table 2 of https://doi.org/10.1186/s12877-019-1291-z.

My question is which is the right way of computing those CI, if it is possible? I may try to divide the CI for the transition intensity in the numerator by the CI for the transition intensity in the denominator with the opposite order (so Lower/Upper and Upper/Lower), but is this correct? If not, is there another way? 

Thank you in advance for your time!

**Comment by iago-pssjd** [comment]
I have just found the function `qratio.msm`. I'll keep the issue open, just for confirmation.

Thank you for the package and help.

**Comment by chjackson** [comment]
That is the one.  See the [help page](https://chjackson.github.io/msm/reference/qratio.msm.html) for how the CI calculation works here.
