### ISSUE TITLE
error in print method for hmmMV

### ISSUE THREAD

**Issue by wjchulme** [chjackson/msm#16]
Creating a `hmmMVdist` object to pass to the `hmodel` argument in `msm` for a multivariate HMM will return an error if printed in the console. Looks like an issue with `print.hmmdist`. For example:

     hmmMVobj <- hmmMV(hmmNorm(mean=1, sd=3),  hmmNorm(mean=0, sd=1) )
     hmmMVobj

    ##>Hidden Markov model distribution
    ##>
    ##>Error in if (x$label == "categorical") paste("P(", seq(x$pars[1]), ")",  : 
    ##>  argument is of length zero

Cheers

**Comment by chjackson** [comment]
This is fixed in the latest commit I think.  The bug was that I'd forgotten to add the print method for hmmMVdist to the NAMESPACE.

**Comment by wjchulme** [comment]
Can confirm this is fixed - thanks
