### ISSUE TITLE
Predicting HMM state probabilities with new data

### ISSUE THREAD

**Issue by wjchulme** [chjackson/msm#18]
Say we have an hmm, fitted using `msm` on `olddata`:

    fittedhmm <- msm(response ~ time, subject = subject, data = olddata, ...)

I'd like to be able to run the Viterbi algorithm with the `fittedhmm` model, but to predict state probabilities for a new dataset, `newdata`, rather than `olddata`. There's two ways I can think of doing this.

**Method 1**

Fit a hmm model with `msm()`:

    fittedhmm <- msm(response ~ time, subject = subject, data = olddata, ...)

Create a dummy, unfitted `msm` object whose initial parameters are taken from `fittedhmm` but are NOT updated to maximise likelihood wrt `newdata`:

    dummyhmm <- msm(response ~ time, subject = suject, data = newdata, 
                                      hmodel = hlist(fittedhmm),
                                      qmatrix = qmatrix(fittedhmm), 
                                      fit = FALSE, 
                                      ...)

where `hlist()` takes the `hmodel.object` from `fittedhmm` and converts it to the correct format (see https://github.com/chjackson/msm/issues/17#issue-408916739). The `fit=FALSE` is the way to prevent the optimsation routine from running, so the model keeps the initial values from `fittedhmm`. Then simply pass this object to `viterbi.msm()`:

    newpredictions <- viterbi.msm(dummyhmm)

**Method 2**

This is neater. Modify `viterbi.msm()` directly so that it has a `data` argument, to be used like this:

    newpredictions <- viterbi.msm(x = fittedmsm, data = newdata)

Looking at the `viterbi.msm()` internals, this would mean creating an object from `newdata` that is the same as the output of `msm:::expand.data()` (which is then passed to `Ccall.msm(params, do.what = "viterbi", ...)` I'm not sure how easy this will be. 

**Fudge**

A simple fudge is to take create a dummy hmm that will convert `newdata` as appropriate (but the fitted parameters are ignored) and run the appropriate parts of `viterbi.msm()` with `fittedhmm` and the dummy hmm, like this:

    library('msm')
    
    ## Simulate data from a Markov model
    nsubj <- 30; nobspt <- 5
    sim.df <- data.frame(subject = rep(1:nsubj, each=nobspt),
                         time = seq(0, 20, length=nobspt))
    two.q <- rbind(c(-0.1, 0.1), c(0, 0))
    
    set.seed(123)
    dat <- simmulti.msm(sim.df[,1:2], qmatrix=two.q, drop.absorb=FALSE)
    dat$obs1[dat$state==1] <- rbinom(sum(dat$state==1), 40, 0.1)
    dat$obs1[dat$state==2] <- rbinom(sum(dat$state==2), 40, 0.5)
    
    newdat <- simmulti.msm(sim.df[,1:2], qmatrix=two.q, drop.absorb=FALSE)
    newdat$obs1[newdat$state==1] <- rbinom(sum(newdat$state==1), 40, 0.1)
    newdat$obs1[newdat$state==2] <- rbinom(sum(newdat$state==2), 40, 0.5)
    newdat<-subset(newdat, subject<16) #just to check it works on different sized data
    
    ## Fitted model
    fittedmsm <- msm(obs1 ~ time, subject=subject, data=dat, qmatrix=two.q,
                     hmodel = list(hmmBinom(size=40, prob=0.2),
                                    hmmBinom(size=40, prob=0.2))
                    )
    
    ##Dummy model to process newdata in the right way (fitted parameters are ignored)
    dummymsm <- msm(obs1 ~ time, subject=subject, data=newdat, qmatrix=two.q,
                    hmodel = list(hmmBinom(size=40, prob=0.2),
                                  hmmBinom(size=40, prob=0.2))
                   )
    
    
    # modified version of viterbi.msm()
    
    viterbiout <- msm:::Ccall.msm(fittedmsm$paramdata$opt$par,
                                  do.what = "viterbi",
                                  msm:::expand.data(dummymsm),
                                  fittedmsm$qmodel, fittedmsm$qcmodel, fittedmsm$cmodel, fittedmsm$hmodel, fittedmsm$paramdata
                                 )
    
    stateprobs <- data.frame(subject = dummymsm$data$mf$"(subject)",
                             time = dummymsm$data$mf$"(time)",
                             observed = dummymsm$data$mf$"(state)",
                             fitted = viterbiout[[1]]+1,
                             pstate = viterbiout[[2]]
                            )
    
    head(stateprobs)
    
    #>  subject time observed fitted     pstate.1  pstate.2
    #>1       1    0        5      1 1.000000e+00 0.0000000
    #>2       1    5       18      2 6.994981e-08 0.9999999
    #>3       1   10       19      2 5.396904e-16 1.0000000
    #>4       1   15       23      2 6.162963e-28 1.0000000
    #>5       1   20       23      2 1.607795e-39 1.0000000
    #>6       2    0        3      1 1.000000e+00 0.0000000

This example demonstrates the desired output but I'd obviously want to stripe away all the unneccesary parts for the conversion of `newdata`, rather than passing it through `msm` every time. 

I'll probably try to put something together for method 2. If you have any advice before I get started I'd be very happy to hear it.

Cheers!

**Comment by chjackson** [comment]
The "fudge" looks the simplest to me!  A large part of what the `msm()` function does is to process the data given the model specification, so I suspect it would be hard to abstract all that out.

You could do as is done in `boot.msm` to run an existing model with a new dataset, e.g. `boot.data`: 

```
x$call$data <- substitute(boot.data)
res <- try(eval(x$call))
expand.data(res) 
```

You can already prevent optimisation with `msm(..., fixedpars=TRUE)`, so you'd also specify `x$fixedpars <- TRUE` above before evaluating the new call. 

I like the idea of having a `newdata` argument to `viterbi.msm`, so perhaps that could be coupled with the above method for converting the data.

**Comment by chjackson** [comment]
Resolved by https://github.com/chjackson/msm/pull/19
