### ISSUE TITLE
Error in if (gen.inits) { : argument is not interpretable as logical with hmmMV

### ISSUE THREAD

**Issue by AA221479** [chjackson/msm#23]
Hello,

I am trying to fit a model with two continuous gaussian outcomes from a HMM. I am following the Example 2 in help(hmmMV) but replacing hmmBinom by hmmNorm.

Here is the code and the data file for which I get this error message:

```
In addition: Warning message:
In if (gen.inits) { :
  the condition has length > 1 and only the first element will be used
```
Thank you in advance for any insight!

```
read.table(file = "df_example_msm.txt", sep ="\t")
head(df)
#           X1          X2      time X4 ID
# 1 0.00042458 -0.04983110 20.018889  C  1
# 2 0.00060557  0.01430985 20.027222  C  1
# 3 0.00181100  0.00416775 20.275000  C  1
# 4 0.01989629 -0.00678782  6.779167  C  2
# 5 0.01989629 -0.00678782  7.413056  C  2
# 6 0.02091527 -0.01099738  7.443333  C  2

df$obs <- cbind(obs1=df$X1, obs2=df$X2)
k=2 #nb. of states
q <- matrix(1, ncol=k, nrow=k)     #specifying allowed transitions. Also if gen.inits=T, used for initial value (excep for diagonal values)
m1=mean(df$X1,na.rm=T)
s1=sd(df$X1,na.rm=T)
m2=mean(df$X2,na.rm=T)
s2=sd(df$X2,na.rm=T)

mod <- msm(obs ~ time, subject=ID, data=df, qmatrix=q,
           hmodel <- list(hmmMV(hmmNorm(mean=m1, sd=s1),hmmNorm(mean=m2, sd=s2)),
                          hmmMV(hmmNorm(mean=m1, sd=s1),hmmNorm(mean=m2, sd=s2))),
           control=list(maxit=10000))
```

[df_example_msm.txt](https://github.com/chjackson/msm/files/4299600/df_example_msm.txt)

**Comment by chjackson** [comment]
You've written `hmodel <-` instead of `hmodel = ` in the call to `msm`.  It works for me with that fixed!  The error message is technically correct, because the erroneous object appears in the position where the `gen.inits` argument is expected to be - it's expecting a `TRUE` or a `FALSE`, but it found the object that you assigned to `hmodel` instead.

**Comment by AA221479** [comment]
Sure, you're completely right, that works for me too. I was having some convergence problems so tried to simplify the model, and in the process I pasted the definition of hmodel into the call to msn without realizing of the <-
Thank you for your time and apologies!
