### ISSUE TITLE
initial value in 'vmmin' is not finite

### ISSUE THREAD

**Issue by MThomas312** [chjackson/msm#25]
Hi,

With the following data I get the error 'initial value in 'vmmin' is not finite' and with the following Q of allowed transitions.

Q <- rbind(c(0,1,0,1),
           c(0,0,1,1),
           c(0,1,0,1),
           c(0,0,0,0))
[partdata.zip](https://github.com/chjackson/msm/files/4941580/partdata.zip)

With a less restrictive Q I get the 'liklihood overflow error' however a less restrictive model isn't clinicly accurate.

Please could you advise?

Many thanks

**Comment by chjackson** [comment]
This works for me.  Did you not do `gen.inits=TRUE`?  The estimated intensities are a long way from 1, as the time unit is small. 

```
partdata <- read.csv("partdata.csv")
Q <- rbind(c(0,1,0,1),
           c(0,0,1,1),
           c(0,1,0,1),
           c(0,0,0,0))
msm(state ~ time, subject=Animal_ID, data=partdata, gen.inits=TRUE, qmatrix=Q)
```

**Comment by MThomas312** [comment]
That's fixed the issue, yes I was missing that. Many thanks!
