### ISSUE TITLE
Change reference value of covariates that are factor type

### ISSUE THREAD

**Issue by ghost** [chjackson/msm#29]
Good night,

How can I change the reference value it takes from the covariates that are factors?

**Comment by chjackson** [comment]
This is a general R question, not specific to msm.   Suppose your dataset is called `dat` and the factor is called `x`.  Use `dat$x <- relevel(dat$x, ...) ` function to change the reference level, or `dat$x <- factor(dat$x, levels=...)` to change the order of the levels.
