### ISSUE TITLE
Specifying covariates for qmatrix.msm and ppass.msm in models with piecewise constant intensities

### ISSUE THREAD

**Issue by fintzij** [chjackson/msm#31]
Hello,

I am running into a strange problem when fitting models with a time constant binary covariate as well as piecewise constant intensities. When I set the value of the covariate, e.g., in qmatrix.msm, the intensities for some transitions can possibly be either both greater or less than the intensity for the mean value of the covariate. This results in very strange estimates of first passage probabilities and other quantities. I think I must be doing something wrong in my function calls?

As an minimal working example, I've modified the sex-adjusted cav model from the msm manual and inserted a changepoint at 10 years. The transition intensities for males and females are both lower than the transition intensity at the mean value of sex, as are the first passage probabilities. 

~~Edit: Also applies to total length of stay.~~

Thanks!
Jon

```
library(msm)

# intensity matrix from the msm manual
Q <- rbind ( c(0, 0.25, 0, 0.25),
             c(0.166, 0, 0.166, 0.166),
             c(0, 0.25, 0, 0.25),
             c(0, 0, 0, 0))

# model with sex + piecewise constant intensities and a changepoint at 10 years
cavsex.msm <- msm( state ~ years, subject=PTNUM, data = cav,
                   qmatrix = Q, deathexact = 4, covariates = ~ sex, pci = 10)

# get rate matrices - transition intensity from 2-3 at the mean value of sex is greater than when sex = 0 or 1
qmatrix.msm(cavsex.msm)
qmatrix.msm(cavsex.msm, covariates = list(sex = 0))
qmatrix.msm(cavsex.msm, covariates = list(sex = 1))

# similarly, the first passage probability for 2-3 is much higher when using the average value of sex
ppass.msm(cavsex.msm)
ppass.msm(cavsex.msm, covariates = list(sex = 0), tot = 10)
ppass.msm(cavsex.msm, covariates = list(sex = 1), tot = 10)
```

**Comment by fintzij** [comment]
Hello, 

Just following up on this. I think my edit regarding total length of stay was incorrect. I am running into what I think is a separate issue with the totlos.msm function in which the analytic results do not match the estimates obtained by numerical integration. The results obtained by numerical integration, however, do seem to make sense in the context of covariates + piecewise constant intensities. 

Adding to the previous example:
```
totlos.msm(cavsex.msm, start = 2, tot = 10, num.integ = F)
totlos.msm(cavsex.msm, start = 2, tot = 10, num.integ = T)
```

**Comment by chjackson** [comment]
Printing the fitted model object `cavsex.msm` in this case shows some extreme estimates and wide confidence intervals, which tells you the model is not identifiable.   I would guess it's those extreme estimates which make the numerical integration go wrong.

**Comment by fintzij** [comment]
Hmm, that certainly seems to be an issue for the confidence intervals. Not sure I entirely understand why the point estimates for total length of stay are so different since those are computed after the model has been fit. Is the difference in the point estimates just due to that piecewise constant intensities aren't yet accommodated in the analytic solution for total length of stay?

The discrepancy between numerical integration and the analytic solution also comes up in the project I'm working on (apologies, I would have posted that except that the data and analysis are highly sensitive). In that case, there are no extreme values in the confidence intervals, and I have considerably more data. If there are no other indications of model degeneracy, do you think it would be safe to attribute the discrepancy in the point estimates to the analytic solution not being implemented for piecewise constant intensities yet? In this case, would it be safe to trust the point estimates from the numerical integration method? I've worked up a bootstrap method for getting the confidence intervals so I think it might be OK as long as I can trust the point estimates. 

To the original question at the top of the thread, I see that piecewise constant intensities aren't yet accommodated by the first passage probability function so I'll probably end up hacking that on my own. Is there another function where this is implemented that I could use as a template for how to preprocess a fitted object to generate what I'd need to feed to pmatrix.piecewise.msm()?

**Comment by chjackson** [comment]
The point estimates are meaningless though if the model is not identifiable.  Or if the likelihood is nearly flat, then the claimed "estimate" is less likely to be the true maximum, if such a maximum even exists.  Here the "estimated" hazard ratio for the period 2 effect on the 3-2 transition rate is 442.  Such large numbers may cause the numerical integration involved in calculating the total length of stay to behave badly. I would rather trust the analytic solution.  totlos.msm does fully support "pci" models as documented.

**Comment by fintzij** [comment]
Apologies, in that case I must be specifying something incorrectly in the call to totlos.msm because the function is definitely not recognizing the changepoints in models with piecewise constant intensities. It is only using the initial intensity matrix from the first time interval, (0,10] in this example.

Here's the call to totlos.msm:
```
#debugonce(totlos.msm) # uncomment to enter debug mode
totlos.msm(cavsex.msm, start = 2, tot = 20, covariates = list(sex = 0))
```

In the loop on line 64 of the function (counting lines in the debugger), npieces is equal to 1, so we are only grabbing one intensity matrix.  The intensity matrix for this single interval, which we grab on line 67, denoted Q, is exactly the matrix that we would obtain if we ask for the matrix in the first time interval:
```
qmatrix.msm(cavsex.msm, ci = "none", covariates = list(sex = 0, "timeperiod[10,Inf)" = 0)) 
```

Should I be specifying piecewise.times and piecewise.covariates explicitly? The documentation indicates not, but I don't see what to change in the model call.

Thanks

**Comment by chjackson** [comment]
You're completely right - sorry and thanks for being persistent!  I had just neglected to fill in the piecewise times and covariates.  It worked with numerical integration because that worked by calling pmatrix.msm, which recognises pci models  properly.   This should be fixed in dfa3bf7 .

For the first passage probs, this comment I had left above the source for `ppass.msm` may or may not help you...
```
## TODO time-inhomogeneous models.
## Do msm.fill.pci.covs to get covariate list
## Get list of Qs by calling qmatrix.msm for each member of this list
## Zero out the appropriate rows
## Supply this to pmatrix.piecewise.msm, which will call pmatrix.msm
```

**Comment by fintzij** [comment]
No worries!!!

I'll give it a shot and post what I come up with. 

Thanks again for your help!

**Comment by fintzij** [comment]
Hi Chris,

I think I have a function for the first passage probabilities. There's a minor hiccup in the pmatrix.piecewise.msm function, which is that the number of states that is used to initialize the P.middle matrix is grabbed from an msm fitted object (line 1095). However, in this case I am passing a list of intensity matrices to pmatrix.piecewise.msm and leaving the x argument to the function as NULL. Hence, `P.middle <- diag(x$qmodel$nstates)` on line 1095 returns a 0x0 matrix. This could be resolved by generating P.middle with, e.g.,  

```
P.middle <- 
    if(is.null(x)) {
        diag(nrow(qlist[[1]]))
    } else { 
        diag(x$qmodel$nstates)
    }
```

Cheers,
Jon

**Comment by chjackson** [comment]
Thanks - do you fancy preparing a pull request for this,  including a test case in tests/testthat/test_models.r ?

**Comment by fintzij** [comment]
Sure, I could do that. Is the `ppass.pci.msm` function fine as written? It only calculates the point estimates of the first passage probabilities (all I needed since I was getting CIs via a bootstrap procedure that I coded up separately). I'm not really sure what to change to get it to play nice with the other routines for getting confidence intervals. 

For a unit test, would testing whether the first passage probabilities in a pci model where we constrain all piecewise constant intensities to be equal gives the same result as a time-homogeneous model suffice?

**Comment by chjackson** [comment]
`ppass.msm` finally now handles time-inhomogenous models in the development version, see commit https://github.com/chjackson/msm/commit/69ce89ca1fb68e0c5b69cf40f16cf93261150edc .   Thanks @fintzij for working on this!
