### ISSUE TITLE
Analysing multicentric panel data with msm

### ISSUE THREAD

**Issue by DamienGeorges** [chjackson/msm#32]
## sugested tag -> questions

Hi,

We planed to use msm package to infer anal HPV infection and clearance rates from panel data coming from different study/center. 
The idea is to conduct a kind of meta-analysis of infection and clearance rates.
Centers are very heterogeneous in term of number of patients and follow-up duration.

Is there a smart way to handle such data within msm framework?
Would you sugest to add a 'center' covariate in the model?
Would it be better to analyse centers independently and conduct a classical rate meta-analysis in a second time?

Thanks a lot for this excellent package and the kind assistance you provide.

With best regards,
Damien

**Comment by chjackson** [comment]
I've never done anything exactly like this,  but I don't know of any special considerations for msm models in this context, compared to any other kind of meta-analysis situation.  You could analyse centers independently at the cost of loss of precision for each centre-specific estimate, but guarding against inappropriate assumptions about any parameters being shared between the centres.  

Ideally you'd be able to use some kind of random effects model, but msm doesn't support this.  I haven't done it, but I'd consider Stan for this.

**Comment by DamienGeorges** [comment]
Thanks a lot for the feedback. This is helpful. Damien
