### ISSUE TITLE
Never pass a tibble to msm2Surv...

### ISSUE THREAD

**Issue by elfatherbrown** [chjackson/msm#33]
Hi! Thanks for this wonderful package. Im just writing in to say I spent the better part of the last three days attempting to use msm2Surv while passing a tibble as the data argument. This results in the **from** and **to** fields of this line:

`  ## Data frame of observed events
  ev <- data.frame(id=data[!lpt,subject], from=data[!lpt,state],to=data[!fpt,state],
                   Tstart=data[!lpt,time], Tstop=data[!fpt,time], time=data[!fpt,time]-data[!lpt,time],
                   status=rep(1,nev)) `

Overwriting an unused **state** field that ultimatly gets lost as well. This results in everything under that line breaking.

Now, this is not a bug, a dataframe is requested by the function and thats what one should pass it. But most of us I believe use tibbles and data.frames as almost interchangeable: Not so!

ALSO: your follow up time should be ordered before feeding it to this function.

Thanks again!

**Comment by chjackson** [comment]
Thanks for the report.  5e1e156 now does a check and coerces tibbles to data frames in this function.
