### ISSUE TITLE
Combining multiple plot.prevalence.msm plots 

### ISSUE THREAD

**Issue by lizacoyer** [chjackson/msm#34]
Hi, 

First of all - great package and page. I'm relatively new to R, and was trying to combine several prevalence plots in 1 plot (depending on subset and covariate value), but am having a hard time changing the `plot.prevalence.msm()` function to allow this, as I don't have the underlying code for `observed.msm()` and `expected.msm()`. I was thinking, is there an easier way of combining the plots, for example similar to how this is done in `ggplot2` ?

Just to make it more concrete, I am using a two-state model without absorbing state. I have specified `pci` cut-offs and 1 covariate with 6 levels, let's call the covariate district. I would like to plot the observed and expected prevalence over time per district. 

The `msm` object I specified accordingly:
```
twoway.q <- rbind(
  c(-0.24, 0.24), 
  c(0.1, 0.1))

districts.msm.pci <- msm(state ~ td1jan, 
                       subject = id,
                       data = helius.inc, 
                       qmatrix = twoway.q, 
                       obstyp = 1, 
                       pci=c(0.5,0.75,1),
                       covariates = ~ district)
```

The plot for one of the districts would be:
```
plot.prevalence.msm(districts.msm.pci, mintime=0, maxtime=2,
                      xlab="Years since 1 jan 2020", ylab="Prevalence (%)",
                      subset = id.districtS,
                      covariates = list(district="South"))
```

Thanks a lot in advance!

**Comment by chjackson** [comment]
You can use internal functions from a package by using the `:::` operator.  So if you're happy with editing `plot.prevalence.msm` then it might be easiest to replace `observed.msm` by `msm:::observed.msm` and `expected.msm` by `msm:::expected msm` in the code.     

Though you will end up with nicer looking plots if you took the output from `prevalence.msm`, rearranged it in "tidy data" format and used `ggplot`.   If I were writing the package now it would be more tidy-friendly!

**Comment by lizacoyer** [comment]
Awesome, this really helped, thank you for your very quick reply. I indeed ended up using `prevalence.msm` so I could use `ggplot2`.  The  `:::` operator advice was also helpful, because I used it to create more timesteps in `prevalence.msm`.
