### ISSUE TITLE
`ematrix.msm` returns `NULL` on `cav`-example

### ISSUE THREAD

**Issue by CGMossa** [chjackson/msm#38]
Hey! I'm not sure this is supposed to happen:

``` r
library(msm)
Q <- rbind (c(0, 0.25, 0, 0.25),
            c(0.166, 0, 0.166, 0.166),
            c(0, 0.25, 0, 0.25),
            c(0, 0, 0, 0))
cav.msm <- msm::msm(state ~ years,
               subject = PTNUM,
               covariates = ~sex,
               data = cav,
               qmatrix = Q,
               deathexact = 4)
msm::ematrix.msm(cav.msm)
#> NULL
```

<sup>Created on 2021-09-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by chjackson** [comment]
There is no misclassification in the model that you have specified, and it is not documented what `ematrix.msm` should return in that case.   What would you expect it to return instead?  An identity matrix?

**Comment by CGMossa** [comment]
Thanks for the answer. I just didn't understand this... But I cannot see how I can make the `cav`-example showcase this output. I tried by using a `qmatrix` that is 0 in some entries, where it should be non-zero. That didn't provoke anything.

**Comment by chjackson** [comment]
I don't understand what you mean by "showcase this output", sorry.  Could you explain what output you are trying to produce?

**Comment by CGMossa** [comment]
How do I make `ematrix` show anything other than `NULL`?

I'm trying to explore this package and this kind of models, and I'm hitting some things that are probably
holes in my understanding, but I think that's worth exploring. 

Second thing I tried was using `pmatrix` with `ci = "normal"` and only one "t" have a CI, the right is `NA`. But that's a different issue.

**Comment by chjackson** [comment]
I'd recommend learning the package by going step by step through the vignette at 

https://cran.r-project.org/web/packages/msm/vignettes/msm-manual.pdf

`ematrix.msm` only applies to models where the observed states are misclassified, hence have been defined using `msm(..., ematrix=...).`.   Your model above does not have an `ematrix` argument in your `msm` call.   See Section 2.14 for a worked example.
