### ISSUE TITLE
pearson.msm  incorrect number of dimensions

### ISSUE THREAD

**Issue by DongdongMa** [chjackson/msm#4]
> pearson.msm(sp.msm, timegroups=2, transitions=c(1,2,3,4,5,6))
Imputing sampling times after deaths...
Error in dist[1, ] : incorrect number of dimensions

**Comment by chjackson** [comment]
Could you email me a minimal reproducible example please?

**Comment by DongdongMa** [comment]
Hi, I sent my data and model to your official email address.

**Comment by chjackson** [comment]
Thanks for the report.  I think this is fixed now in 0f57abe.

**Comment by DongdongMa** [comment]
Thank you. This function works now.
