### ISSUE TITLE
HMM censoring and obstrue

### ISSUE THREAD

**Issue by helmingstay** [chjackson/msm#40]
I'm working on an infectious disease project that uses a HMM and uses censoring and known states at arbitrary times.  I'm struggling to understand how `obstrue` works in this case. After looking closely at `help(msm)` for argument `obstrue`, my  impression was that A) I needed obstrue==1 for each censored observation, and that B) I could force a censored observation into a given state by providing a single state in the appropriate entry of `censor.states`.  My experience with msm suggests that I'm misinterpreting something.

I've found that I can use censoring to force a given state if I:
* Do *not* provide `obstrue`
* include a vector of length>1 in censor.states, e.g., `censor.states=list(known=c(1,1), other=c(1,2))`

 Notably,  `censor.states=list(known=c(1), other=c(1,2))` does not  behave as expected / as above (but still overrides provided initprobs, though that's a separate issue).

Below is a full example with four possible behaviors (see args commented with `##?`): two different `censor.states`, each with and without `obstrue`. I'm struggling to understand the behavior of each option, and which is appropriate for my use-case. 

Any advice would be appreciated!

```
library(msm)
library(data.table)
set.seed(8)

## msm docs: 
# * obstrue=1 required for censor effects (add note to censor?)
# * censor.state list: length 1 fails without error

## SI model
pars <- within(list(), {
    npair = 50
    q.i = 0.05
    prob=list(S=0.2, I=0.8)
    nstate=length(prob)
    tmax=20
})

subjects <- expand.grid(
    pair = 1:pars$npair,
    group = factor(c('A','B'))
)

## simulate time to infection
subjects <- within(subjects, {
    id <- paste(pair, group, sep='.')
    infect <- rexp(nrow(subjects), pars$q.i)
})
subjects <- data.table(subjects)

## regular observation schedule
obs.time = seq(from=0, to=pars$tmax, by=5)
#obs.time = seq(from=0, to=max(subjects$infect)+10, by=5)

## input to msm: test results conditioned on infection status
panel <- subjects[, by=.(id, group), j={
    time = obs.time
    ## F = S, T = I
    state = (obs.time > infect)
    ## observation process conditioned on state
    obs = rbinom(length(state), 1, 
        ifelse(state, pars$prob$I, pars$prob$S)
    )
    .(time, state, obs)
}]

## censoring: 
## group A starts in known state 1
panel[(group=='A' & time==0)]$obs <- -1
## group B starts in unknown state
panel[(group=='B' & time==0)]$obs <- -2
## Both have unknown observattion 
panel[(time==10)]$obs <- -2

## initial conditions
config <- list(
    qmat = matrix(byrow=T, nrow=.nstate, c(
        ## S-I
        0, pars$q.i*1.2,
        0, 0
    )),
    ## observation model 
    hmod = list(
        S=hmmBinom(size=1, prob=0.1),
        I=hmmBinom(size=1, prob=0.9)
    )
)

result <- msm(data=panel,
    obs ~ time,
    subject=id,
    censor = c(-1, -2),
    ## Informative group-A init 
    ## works as intended
    censor.states=list(c(1,1),c(1,2)),
    ##? behavior differs from above
    # censor.states=list(c(1),c(1,2)),
    ##? how does this work?
    # obstrue = ifelse(obs<0, 1, NA),
    initprobs=c(0.6, 0.4),
    qmatrix=config$qmat,
    hmodel=config$hmod,
    fixedpars=T
)

pred <- merge(
    panel, 
    as.data.frame(viterbi.msm(result)),
    by.x=c('id', 'time'), by.y=c('subject', 'time')
)
```

**Comment by chjackson** [comment]
This report is hard for me to follow, because it's not clear what model you are intending to fit.  What specifically do you know about particular states at particular times?   When you refer to "censored" states, do you mean that you know the true state is within some set, or that the observed state is within some set?

If you know that the true state is within the set in `censor.states`, you should also specify `obstrue=1` on those occasions.

If `censor.states` refers to the set of observed states, there is assume to be a layer of misclassification on top - the likelihood contribution for p(obs|true) at a "censored" data point is summed over the "obs" in `censor.states`.

**Comment by helmingstay** [comment]
Thank you - I misunderstood the interaction between `obstrue` and `censor`. In this case, my intent was to specify states and not observations. I'm submitting a PR with minor suggested clarifications based on your response.

I don't fully follow your comments re `a layer of misclassification`. What does "true" refer to in "p(obs|true)" here?

**Comment by chjackson** [comment]
`true` refers to the hidden states, which follow a Markov model.  `obs` are the measured states, whose values are generated from a model conditionally on the true state.  The `censor` mechanism can be used in two alternative ways in hidden Markov models - either to specify (a) that the true state is within the `censor.states` set, or (b) that the measured value is within the `censor.states` set.   

In case (b) we don't necessarily know that the true state is within `censor.states`.  The likelihood contribution for that measurement involves summing the probability of the observed value (given the true state) over all potential observed values in `censor.states`.   The full likelihood for that individual then involves a sum over all potential pathways between true states, as in any hidden Markov model.

**Comment by helmingstay** [comment]
Thanks for the clarification, much appreciated.

**Comment by helmingstay** [comment]
Judging by the output of `viterbi.msm`, I'm still not able to force a particular observation into a particular state using `censor`, `censor.states`, and `obstrue`. 

Reusing my revised example from #41, below I expect members of group B to start in state 2. However, `viterbi.msm` shows the probability of state 2 as 0 for all cases at t==0, and the fitted state as state 1.

```
library(msm)
set.seed(8)

## SI model
pars <- within(list(), {
    npair = 50
    ## transition rate
    q.i = 0.05
    prob=list(S=0.2, I=0.8)
    nstate=length(prob)
    tmax=20
})

subjects <- expand.grid(
    pair = 1:pars$npair,
    group = factor(c('A','B'))
)

## simulate time to infection
subjects <- within(subjects, {
    id <- paste(pair, group, sep='.')
    infect <- rexp(nrow(subjects), pars$q.i)
})
subjects <- data.table(subjects)

## regular observation schedule
obs.time = seq(from=0, to=pars$tmax, by=5)

## input to msm: test results conditioned on infection status
panel <- lapply(1:nrow(subjects), function(ii) {
    x <- subjects[ii,]
    ## subject state at time t
    ## F = S, T = I
    state = (obs.time > x$infect)
    ## observation process conditioned on state
    obs = rbinom(length(state), 1, 
        ifelse(state, pars$prob$I, pars$prob$S)
    )
    data.frame(id=x$id, group=x$group, time=obs.time, state=state, obs=obs)
})
panel <- do.call(rbind, panel)

## censoring: 
## group A starts in known state 1
panel <- within(panel, {
    obs[(group=='A' & time==0)] <- -1
    ## group B starts in unknown state, not observed
    obs[(group=='B' & time==0)] <- -2
})

## initial conditions / observation model
config <- list(
    qmat = matrix(byrow=T, nrow=pars$nstate, c(
        ## S-I
        0, pars$q.i*1.2,
        0, 0
    )),
    hmod = list(
        S=hmmBinom(size=1, prob=0.1),
        I=hmmBinom(size=1, prob=0.9)
    )
)

result <- msm(data=panel,
    obs ~ time, subject=id,
    censor = c(-1, -2),
    ## group A: start in state 1 
    ## group B: start in state 2
    censor.states=list(c(1),c(2)),
    ## censored values indicate state
    obstrue=ifelse(obs<0, 1, NA),
    qmatrix=config$qmat,
    hmodel=config$hmod,
    fixedpars=T,
)

pred <- merge(
    panel, 
    as.data.frame(viterbi.msm(result)),
    by.x=c('id', 'time'), by.y=c('subject', 'time')
)

## I expect these individuals to be in state 2
subset(pred, group=='B' & time==0) 
```

**Comment by chjackson** [comment]
Just to confirm that estimation and Viterbi prediction are bugged when `obstrue` and `censor` are specified, and `censor.states` contains more than one state for some observations. Currently it is assuming that if `obstrue` is specified, then there is only one state possible, hence it is ignoring `initprobs`. I'm working on a fix.   Thanks for the report.

**Comment by chjackson** [comment]
In https://github.com/chjackson/msm/commit/da6eece3727ed2973bbad697c099dc8e1f70fa8c, in HMMs where some observations are specified as `censor`ed and `obstrue` is set, so that the true state is known to be in `censor.states`, then model fitting and Viterbi prediction should now work properly by using `initprobs`.   `initprobs` is pre-processed in R to define zero probabilities for states that are outside the censor set, and reweighting the probabilities of the other possible states to sum to 1.
