### ISSUE TITLE
 MSM with covariates :

### ISSUE THREAD

**Issue by ChuanhaiXu** [chjackson/msm#43]
Hello Dr. Jackson,
Thank you very much for your excellent work for MSM; I'm a new user of this package and I have faced an issue that I didn't know how to understand.  I want to evaluate the effect of  variates on partial transitions, such as, 
I get the hazard ratios and confidence intervals of age on the first transition, as well as the age and gender on the second transition by code: covariates = list("1-2" = ~ age, "2-3" = ~ age + gender). However, when I add a new transition in the above code: covariates = list("1-2" = ~ age, "2-3" = ~ age + gender, "2-4"= ~ age + gender+education),  I will obtain a new value of the hazard ratios and confidence intervals of age on transition "1-2" , and age, gender on transition "2-3". How should I understand the difference between the two values? If I only want to examine the effect of age, gender on transition "2-3", "2-4", Can I ignore the effect of variables on the transition "1-2", code like this: covariates = list( "2-3" = ~ age + gender+education, "2-4"= ~ age + gender+education)?

**Comment by chjackson** [comment]
If the states are intermittently observed, then the likelihoods for the different transitions cannot be estimated independently of each other - i.e. all data provides information about all parameters simultaneously.  So if you change the model for one transition, then you would also expect the parameter estimates for a different transition to change. 

Beyond that, there's nothing specific to multi-state models, it's just an general issue of statistical model selection.  You should include whatever covariates you think should be scientifically important in your application, and if you want to let the data decide between different models you could use standard tools like AIC or likelihood ratio tests for model comparison.

**Comment by Xuch24** [comment]
Hello Dr. Jackson,
Thank you for your reply. I used the following code for my research to determine the effect of  covariates on the different transitions. But, the following transitions do not include all the transitions allowed by the qmatrix,(i.e. "1-2","1-3","1-5","2-1","2-4","2-5","3-1","3-4","3-5","4-2","4-3","4-5"). Is the hazard ratio obtained valid?
multi_factors <- msm(state~Time,subject=ID,data=markov4_4,qmatrix=Q,covariates = list(
"1-2"=~age+rgender+hukou+education+satisfied+depression+multimorbidity,
                                                                                                 
"1-3"=~age+rgender+hukou+education+satisfied+depression+multimorbidity,
                                                                                                 
"2-1"=~age+rgender+hukou+education+satisfied+depression+multimorbidity,
                                                                                                 
"2-4"=~age+rgender+hukou+education+satisfied+depression+multimorbidity+night_sleep+fall,
                                                                                                 
"3-1"=~age+rgender+hukou+education+satisfied+depression+multimorbidity,
                                                                                                 
"3-4"=~age+rgender+hukou+education+satisfied+depression+multimorbidity+night_sleep+fall,
                                                                                                 
"4-2"=~age+rgender+hukou+education+satisfied+depression+multimorbidity+night_sleep+fall,
                                                                                                
 "4-3"=~age+rgender+hukou+education+satisfied+depression+multimorbidity+night_sleep+fall),
control=list(maxit=20000,fnscale=25000))

**Comment by chjackson** [comment]
OK I see what you mean.  That is a valid model specification.  The transitions you haven't supplied covariates for won't have covariates on them.   See help(msm), section "covariates".
