### ISSUE TITLE
simmulti.msm fails with hmmMV in hmodel

### ISSUE THREAD

**Issue by helmingstay** [chjackson/msm#47]
I'm preparing an MWE using hmmMV for issue #46, and I get an error when I use `hmmMV` in  `simmulti.msm(..., hmodel=list())`.  I have a working example of `msm` using real data and a formulation of `hmodel` similar to what's shown below. I've looked over `help("simmulti.msm")`, and I don't see any specific mention of `hmmMV`. Is this use-case supported? Or perhaps I'm making a silly mistake here?
 
```
library(msm)
set.seed(8)

pars <- within(list(), {
    npair = 20
    deltat=5
    tmax=20
    ## transition rate
    q = 0.05
})

qmat <- rbind(
    c(0, pars$q),
    c(0, 0)
)

## data input to simmulti.msm
sim.grid <- with(pars,
    expand.grid(time=seq(0,tmax,by=deltat), subject=1:npair)
)

sim.dat <- simmulti.msm(sim.grid, qmat,
    hmodel=list(
        S=hmmMV(
            A=hmmBinom(size=1, prob=0.1),
            B=hmmBinom(size=1, prob=0.2)
        ),
        I=hmmMV(
            ## sim uses larger size here
            A=hmmBinom(size=2, prob=0.8),
            B=hmmBinom(size=1, prob=0.6)
        )
    )
)
```

Result:
```
Error in if (!(hmodel[[i]] == identity && (length(hmodel[[i]]) ==  :
  missing value where TRUE/FALSE needed
```

**Comment by chjackson** [comment]
Yes hmmMV is just not handled here.  I've put a note in the help and an appropriate error message in https://github.com/chjackson/msm/commit/7fe34fdbd96d1168ca876e3e3a49e98342cacbc9
