### ISSUE TITLE
Using inverse probability weight in MSM models

### ISSUE THREAD

**Issue by axinaxia** [chjackson/msm#50]
Hi Dr.Jackson, 

I wonder if it's possible to use inverse probability weight in "msm"? If yes, how? There is no "weight" argument in msm, right? I am thinking of using inverse probability weight to deal with missing and dependent censoring.

I appreciate any help you can offer!

**Comment by chjackson** [comment]
There's no easy interface for weighted estimation in `msm`, though it is technically possible with some fiddly programming from the user.  `msm` can compute the value of a likelihood with subject-specific weights easily, but you'd need to optimise this by hand using `optim()`.   I don't see a way of doing observation-specific weights though. 

Suppose for the moment there are no covariates, you are just estimating intensities.   You could define the minus log likelihood as a function of the vector of unknown parameters, something like this: 

```
fn <- function(pars){
   q[1] <- pars[1]
   q[2] <- pars[2]
   ## ... etc for the rest of the intensities

   ## ...define the matrix Q here in terms of the little q's
   ## the diagonal entries have to be minus the sum of the rest of the row...

   ## note with "fixedpars=TRUE" this doesn't do any optimisation
   ## just calculates the likelihood at values Q
   mod <- msm(..., qmatrix=Q, fixedpars=TRUE,...)

   logLik(mod, by.subject=TRUE)
   - sum(w*lik)
}
```

This is the function to be minimised by `optim()`.  Then set `inits` to be a vector of initial guesses at what the intensities should be, and call 

```
optim(inits, fn)
```

If there are covariates, `pars` would have further elements defining the covariate effects, which would be used to form a further `covinits` argument to msm.   Though it will be fiddly to build up all these arguments!

**Comment by axinaxia** [comment]
Thank you, Dr.Jackson, for your explanations!

**Comment by lingwany98** [comment]
I am a  little confused, does the w in "sum(w*lik)"  here refer to the weights? If there are some covariates, how do I use the "covinits" argument? I'm a novice and I don't know if these questions are appropriate... Thanks again for your work!

**Comment by chjackson** [comment]
Yes, `w` is a vector of the subject-specific weights.   The `covinits` argument is documented in the help page for the `msm` function, do `help(msm)` or `?msm` in R.   

If you are new to `msm` I'd also recommend following the [course notes here](https://chjackson.github.io/msm/msmcourse/).

**Comment by chjackson** [comment]
Subject-specific weights are now implemented in https://github.com/chjackson/msm/commit/4e1910d1c5f15f4702e21b77a40a236de456bd63 and subsequent commits.
