### ISSUE TITLE
Comparing a multivariate HMM and univariate HMM for binary classification

### ISSUE THREAD

**Issue by antoniogt** [chjackson/msm#52]
I have trained three HMMs to do binary classification, all with the same data. Now, one HMM is multivariate (uses two variables of the same data) and I have trained it only with data from one class. For data from this same class, I have trained a univariate HMM (using one variable of the two taken in the multivariate HMM). In addition, for the other class, I have used a univariate HMM only.

Now, I want to compare whether the final classifier (which is formed by two HMMs, one for each class) using the multivariate HMM and the other univariate HMM is better than using the two univariate HMMs.

The issue is that for the multivariate HMM I get much higher likelihoods than for the univariate HMMs in the test set, so it seems that you cannot compare in such a simple way a multivariate HMM and a univariate HMM.

So, I would like to know exactly how the msm package calculates the likelihood in the multivariate HMMs, in case I need to apply any changes to the likelihood to compare it with the univariate HMMs.

**Comment by chjackson** [comment]
In all HMMs in `msm`, there is only one hidden state at each time, but there may be multiple outcomes generated independently conditionally on that hidden state.   The likelihood for an individual's data $Y$ is $\sum_r p(Y|S_r)p(S_r)$ where $S_r$ are the alternative possible pathways through hidden states. In a multivariate model, $P(Y|S_r)$ will be the product of univariate components.   

The multivariate model accounts for correlation in the observations through conditioning on the underlying state.  So the log likelihood won't be the same as the sum of the corresponding univariate log likelihoods.   It should be comparable though.   Perhaps it just fits a lot better in your example?

**Comment by antoniogt** [comment]
When I try to perform inference with my test data, by simply calculating the likelihood associated with each sequence of data from the test individuals and associating to each individual the class of the individuals used to train the HMM that gives us the highest likelihood, I get much higher probabilities for the univariate HMM than for the multivariate HMM, so all individuals are classified with the class of the individuals from the univariate HMM, thus having a very bad joint classifier (using the multivariate HMM and the univariate HMM).

**Comment by chjackson** [comment]
I don't have experience with this style of modelling, so I'll leave the issue open in case anyone else does.  If you spot a bug, can you provide a minimal reproducible example?

**Comment by chjackson** [comment]
Closed due to inactivity
