### ISSUE TITLE
log(hazard ratios) and standard errors?

### ISSUE THREAD

**Issue by vcallier** [chjackson/msm#54]
Hello! 

I am using the msm package to model a population of hospitalized patients whose outcomes are either death or discharge. I have a covariate x for which the msm output provides the hazard ratio and 95% CI. Is there a way to obtain the standard error for the hazard ratio?  
What I am really looking for is, Is there a way to obtain the log(hazard ratio) and the standard error for the log(hazard ratio) ? 
Thanks for your help!!

**Comment by chjackson** [comment]
The 95% CIs for parameters on the log scale are calculated as estimate plus or minus 1.96 (i.e. qnorm(0.975)) times the standard error.  Also, the standard errors of log hazard ratios are stored in the `$QmatricesSE` component of the fitted model object, see `help(msm.object)`.

**Comment by vcallier** [comment]
Thanks!!
