### ISSUE TITLE
Add electronic health records to panel data?

### ISSUE THREAD

**Issue by axinaxia** [chjackson/msm#58]
Hi Dr. Jackson,

When we model panel data with "MSM" and assume arbitrary observation times (exacttimes=F), is it worth adding available electronic health records to the panel data? For instance, adding national electronic health records and information from certificates of cause of death to cohort data collected regularly to identify as many disease cases as possible and also "impute" missing disease states due to dropout and death?

If it is beneficial to add those electronic health records, should they be added to the data as additional observations in practice?

Thanks!

Xin

**Comment by chjackson** [comment]
I can't answer whether it's appropriate to use this data.  That's not an msm question and would be better answered by people who are more familiar with the data you are suggesting to use.   When you're combining multiple sources of data, you have to be alert for potential biases, e.g. how are the data sampled / observed, and are they describing the same population?     In a multistate model you also have to assume the observation times are not informative. 

If you have a question about how to use `msm` for a specific data structure, could you be more clear?  If the electronic health records are panel data then you can add them as additional observations, assuming there are no biases.   If they represent exact transition times you have to make sure `obstype` is set appropriately.

**Comment by axinaxia** [comment]
Hi Dr.Jackson,

Thank you for your explanations, and sorry for not being clear.

The electronic health records represent exact transition times. So if they are combined with the panel data, the final data will be a combination of arbitrary observation times and exact transition time. 

I know that we can specify the exact transition time for death with the argument "deathexact". However, I don't know how to specify the types the transition times for a state that can have both arbitrary and exact transitions times due to the combination of panel data and electric record data. It seems "obstype" should be used in this case, but I didn't find enough information to know how to use "obstype" in my case properly.

I am really grateful for your advice!

Xin

**Comment by axinaxia** [comment]
Thank you, Dr.Jackson, for your quick reply. If I understand correctly, I should create a variable called "obstype" in the data, which corresponds to the types of observation times. In addition, I need to write "obstype", but not "obstype=1/2/3" or "obstype=c(1,2,3)", in msm().

Xin

**Comment by chjackson** [comment]
Yes, if the variable is called `"obstype"` then call `msm(..., obstype=obstype)`

See the tutorial at https://chjackson.github.io/msm/msmcourse/msmbasic.html#obstype

**Comment by axinaxia** [comment]
Thanks a lot for your suggestions! They are very helpful.

Xin
