### ISSUE TITLE
Estimating a physical exercise model

### ISSUE THREAD

**Issue by mohammedsaqr** [chjackson/msm#59]
I am trying to fit a model where three states of physical exercise are present 3=active, 2=moderate, 3=inactive
I am assuming that each state is more likely to stay, but also change to the adjacent state or less likely that they change from e.g., active to inactive. I am also assuming that the moderate state is more volatile and can move up or down easier. This is how my qmatrix looks like, 

QM <- rbind ( c(0.7, 0.15 , 0.15),
            c(0.25, 0.5, 0.25),
            c(0.25, 0.25,  0.7))

The time is discrete time measurements which is at one month exactly.

MSMtrans <- msm(state ~ time, subject=User, qmatrix = QM ,data = Head, exacttimes=TRUE )

The question is am I specifying the model correctly ?

I get different results than the one on the vignette, but more problematic – to my understanding– is that I get some results that I can not explain

For example, I get the time points as continuous, see below

$prevalences
$prevalences$Observed
     State 1 State 2 State 3 Total
1        110      48      80   238
2.3      102      51      85   238
3.6      110      52      76   238
4.9      103      52      83   238

The transition probabilities at t4 and forward seems like random i.e., close to 0.3-0.4 all the time

        State 1 State 2 State 3
State 1    0.49    0.20    0.31
State 2    0.48    0.23    0.29
State 3    0.47    0.18    0.35

I added a co-variate which was  for an incentive but I am getting transition probabilities  in negative 
For example, 
State 1 - State 1 -0.32211 (-0.365524,-0.28386)                       

I would assume that people would stay in the same or be more likely to be affected.

I would greatly appreciate your response

I added some sample of the data anonymized and synthetic, so, it should do the job

[Headdata.csv](https://github.com/chjackson/msm/files/9173426/Headdata.csv)

**Comment by chjackson** [comment]
I think you are misinterpreting what msm does.  It fits continuous-time models - the intensities Q are not probabilities, but intensities.   This is explained in the documentation.   These [course notes](https://chjackson.github.io/msm/msmcourse/) may help to understand it.   

If you have discrete-time data, and the aim is to estimate discrete-time transition probabilities, I don't think msm is a suitable tool - instead I would use multinomial logistic regression (e.g. [nnet::multinom](https://www.rdocumentation.org/packages/nnet/versions/7.3-17/topics/multinom)) to estimate the probability of the next state, with the current state and covariate values as predictors.

**Comment by mohammedsaqr** [comment]
Thank you very much, I really appreciate your kind and swift response, I read the manual and probably mis-interpreted some mentions of discrete times, e.g., this phrase
"The msm package uses a direct method of calculating likelihoods in discrete or continuous time based on matrix products"
Looking forward to when I get a dataset and use msm with, it I really liked it and how well it was designed.
