### ISSUE TITLE
Model assessment in the case of censored states and different observation times

### ISSUE THREAD

**Issue by axinaxia** [chjackson/msm#62]
Hi Dr.Jackson,

I fitted an msm model in a cohort in which observation time schemes were predetermined by age. Thus, observation times differ between individuals and change over time for a subgroup of individuals. In addition, at each observation time, there were censored states.

I wonder which method I should use to assess goodness-of-fit for this model and what I should consider apart from what you wrote in your msm package manual.

Many thanks!

**Comment by chjackson** [comment]
I can't think of anything specifically about the kind of model you describe.  Differing observation schemes makes it more difficult - there's no generally applicable approach.   I usually find it most helpful to compare predictions of prevalences of states, over time, to "observed" prevalences - though any measure of "observed" prevalence will be approximate if everyone is measured at different times. 

You could also consider alternative model specifications that might be sensible in your application (e.g different covariates? time-inhomogenous? phase-type semi-Markov?) see if they fit better (using e.g. AIC) and make sure the conclusions you care about don't change.

**Comment by axinaxia** [comment]
Thanks a lot for your quick reply! Can you please elaborate on what you mean by phase-type semi-Markov? Can this be implemented in msm?

**Comment by chjackson** [comment]
This model is described fully in the paper by [Titman and Sharples]( https://doi.org/10.1111/j.1541-0420.2009.01339.x) , and can be done in msm, see `help(msm)` , argument `phase.states`.

**Comment by axinaxia** [comment]
Hi Dr.Jackson,

Just one last question on this topic: I understand "observed" prevalence will be approximate, but I don't understand how I should interpret observed prevalence when there are (1) censored states, (2) reversion from a disease state to a healthy state, and (3) the observation interval is large (>5 years apart) in my data.

Could you please give some suggestions?

**Comment by chjackson** [comment]
Do you mean how does the package compute the quantities that are labelled as "observed" prevalences in the output of `prevalence.msm`?   This is explained in `help(prevalence.msm)`.   Basically it assumes either that people stay in the same state between observation times, or assume one transition occurs half way between the observation times (argument `interp`).   Censored states are singly imputed using the most likely value under the fitted model.

**Comment by axinaxia** [comment]
yes, thanks a lot for your explanations
