### ISSUE TITLE
I need help with msm model

### ISSUE THREAD

**Issue by olagunjuahmed** [chjackson/msm#63]
Dear Prof.
I am working with a dataset that record full birth history of women. To simplify the mode, I am trying to use msm to understand the transition between first and the fourth birth.

I guessed that each women spend an average of 4 years before conceiving another child.

I tried to use the msm model, I got the error below:

> Error in optim(control = list(fnscale = 4000), method = "BFGS", par = c(qbase = -1.11788999409401,  : 
  initial value in 'vmmin' is not finite

Please, how do go about this?

**Comment by chjackson** [comment]
See Section 2.12 of the [vignette](https://cran.r-project.org/web/packages/msm/vignettes/msm-manual.pdf) for some advice about when this happens.   The most likely cause is that the model has too many parameters to be estimated from the available data, particularly if the data are intermittently observed.  Check you haven't confused between discrete-time and continuous-time modelling when defining the transition structure. See also these [course notes](https://chjackson.github.io/msm/msmcourse) for some general modelling advice.

**Comment by olagunjuahmed** [comment]
Compliment of the Season!

I observe that the dataset has many parameters as you have discussed, so I selected a fractional part. The model ran successfully.

In the case of this scenario, I am modelling birth history and reversal is not possible in this scenario.

I have a sample output from the model. Please, how can I interpret the output below?

Call:
msm(formula = birth_order ~ interval, subject = caseid, data = dfz1ea,     qmatrix = Q2, deathexact = NULL)

Maximum likelihood estimates

Transition intensities
                  Baseline                 
State 1 - State 1 -1.5891 (-3.7620,-0.6713)
State 1 - State 2  1.5891 ( 0.6713, 3.7620)
State 2 - State 2 -0.1677 (-0.2675,-0.1051)
State 2 - State 3  0.1677 ( 0.1051, 0.2675)
State 3 - State 3 -0.2296 (-0.4397,-0.1199)
State 3 - State 4  0.2296 ( 0.1199, 0.4397)
State 4 - State 4 -0.2142 (-0.5515,-0.0832)
State 4 - State 5  0.2142 ( 0.0832, 0.5515)

-2 * log-likelihood:  120.6017

**Comment by olagunjuahmed** [comment]
Compliment of the Season!

I observe that the dataset has many parameters as you have discussed, so I selected a fractional part. The model ran successfully.

In the case of this scenario, I am modelling birth history and reversal is not possible in this scenario.

I have a sample output from the model. Please, how can I interpret the output below?

Call:
msm(formula = birth_order ~ interval, subject = caseid, data = dfz1ea, qmatrix = Q2, deathexact = NULL)

Maximum likelihood estimates

Transition intensities
Baseline
State 1 - State 1 -1.5891 (-3.7620,-0.6713)
State 1 - State 2 1.5891 ( 0.6713, 3.7620)
State 2 - State 2 -0.1677 (-0.2675,-0.1051)
State 2 - State 3 0.1677 ( 0.1051, 0.2675)
State 3 - State 3 -0.2296 (-0.4397,-0.1199)
State 3 - State 4 0.2296 ( 0.1199, 0.4397)
State 4 - State 4 -0.2142 (-0.5515,-0.0832)
State 4 - State 5 0.2142 ( 0.0832, 0.5515)

-2 * log-likelihood: 120.6017

**Comment by chjackson** [comment]
Closed due to inactivity
