### ISSUE TITLE
Error on observations states with exact transitions

### ISSUE THREAD

**Issue by poradamc** [chjackson/msm#69]
Dear Prof. Jackson,

This is my first time using the msm package.  I am trying to fit an msm model to a dataset describing the decision stages an individual goes through using the Precaution Adoption Model Process as the theoretical framework.  I am trying to establish a baseline model.  I defined the initial transition intensity matrix to indicate which instantaneous transitions were permitted and then used the "gen.inits=True" argument to generate the initial values. I keep receiving the following errors:

(1) _Error in optim(method = "BFGS", control = list(), par = c(qbase = -6.17170317161558,  : initial value in 'vmmin' is not finite_
(2) _Data may be inconsistent with intensity matrix for observations with exact transition times and no misclassification_

In an effort to address the convergence error I collapsed the number of states to eliminate the pairs of states that had little to no frequency counts, however, this did not seem to help.  I did not spend too much time on addressing this error since I figure I need to address error (2) first.

Error (2) points to a pair consisting of a snapshot observation and an exact transition observation not in subsequent states.  There is no instantaneous transition between these two states but there are only 3 states between the two observations and the frequency table indicates there are a fair amount of frequency counts between these two states.  Is there some special consideration I need to take into account when identifying an observation as an exact transition? I could not find anything along these lines in the manual.

I have attached the R script and input file for your review should you have the time to take a look.  I appreciate your time and any suggestions/recommendations you may have.

Thank you!
[syr_msm.zip](https://github.com/chjackson/msm/files/11355904/syr_msm.zip)

**Comment by chjackson** [comment]
For "individual 302708 moves from state 3 to state 6 at observation 4" the error is because `Q[3,6] = 0` and `obstype=2`.   `obstype=2` means that this person stays in state 3 throughout this time interval, then moves to 6, but `Q[3,6]=0` means they have zero probability of moving to 6.   So the model is not valid for the data.  There seem to me many more of these in the data, the error message only identifies the first one it finds. 

For the snapshot observation (WD00474968) it's harder to tell - it looks like the initial values that the software generates are extreme, and some manual trial and error might be necessary to get transition intensities that are plausible.  You want to determine some Q for which the transition probability P(t) = MatrixExp(-Qt) over this observation time interval t is non-zero, and high enough that the observed transition is plausible.

**Comment by poradamc** [comment]
Thank you, Prof. Jackson.  I had misunderstood obstype=2 to mean an exact transition into a given state from the previously allowed state.  This makes much more sense now.

My challenge now seems to be getting the model to converge.  I keep receiving the error that the optimization has probably not converged to the maximum likelihood and that the Hessian is not positive definite. I am manually trying different initial values for Q and got rid of the gen.inits=True argument in the msm function.  In section 2.4 I read that using gen.inits to generate initial values for Q may not give sensible values if there are many changes of states between subsequent observation times which may very well be the case here. Are there any other references you would recommend to derive "sensible" values of Q that will enable the model to converge?  Thank you, again.

**Comment by chjackson** [comment]
Bad convergence is more commonly because the model is too complicated for the data, rather than because of bad initial values.  This is common with intermittently-observed data and complex transition structures, because it is often not clear which transitions actually happened.   I'd advise to simplify your problem so that there is a small number of states and parameters - small enough that you can understand how the parameters are informed by the data.  Then build it back up again until it is too complicated for the data to handle.

**Comment by poradamc** [comment]
Thank you, Prof. Jackson.  I will do that.  I appreciate your prompt response and suggestions.

**Comment by poradamc** [comment]
Dear Prof. Jackson,
I implemented your suggestion of simplifying the model by collapsing the number of states. I ran a 5-state model with two absorbing states. I ran "statetable.msm" to check the number of transitions between each pair of states and the table seemed reasonable. However, when I run msm using the default "BFGS" optimization method, I receive the error "numerical overflow in calculating likelihood".  Following section 2.12 from the msm manual, I tried applying a scaling factor.  When this failed to work, I tried specifying a different optimization method such as "CG" but then received the error "Optimisation has probably not converged to the maximum likelihood - Hessian is not positive definite." Again, I tried to correct this using guidance from section 2.12 but I still could not get it to converge. I then further collapsed the model to 4 states and it converged. However, it seems to me that the 5 stage model is fairly simple and straight forward so I am confused why it may not be converging.  The only way I was able to get it to run was by specifiying "use.deriv=FALSE". However, I don't completely understand what the implications are of not using analytic derivitives in the optimization of the likelihood and am not certain this is the best solution to the lack of convergence.
I have attached the code and data for the 5 stage model.  Any suggestions you may have are greatly appreciated.

Thank you.
[syr_5stage.zip](https://github.com/chjackson/msm/files/11666738/syr_5stage.zip)

**Comment by chjackson** [comment]
Yes I agree this is not a complicated model.  I've just tried fitting this model to random subsets of your data (generated by selecting a random 100 subjects).  

```{r}
subj_ran <- syr_5stage$PolicyNumber %in% sample(unique(syr_5stage$PolicyNumber), 100)
syr_5stage.msm <- msm(Stage_Coded_m2~Days, subject = PolicyNumber, 
                      data = syr_5stage[subj_ran,], qmatrix = Q, gen.inits=TRUE,
                      control=list(maxit=10000,fnscale=10000))
syr_5stage.msm
```
Sometimes it converges, and sometimes it doesn't, depending on which sample of 100 is drawn.   So I'd guess that there is some data somewhere that are "extreme" and don't fit the model very well, leading to this computational overflow.   It might take some trial and error to identify this though, along with some exploratory analysis of the time intervals as well as the counts of transition pairs.

**Comment by poradamc** [comment]
Prof. Jackson,
Thank you for your quick response. By "extreme" data, do you mean that there might be observations for some subjects where the step between observations is too large?  For example, a subject with two observations going from state 1 to state 5. 
Also, would you mind explaining the use.deriv argument and when it is appropriate to change it from the default?

Thank you.

**Comment by chjackson** [comment]
There should be an informative error message if there are any data with transitions that are disallowed by the model. 
In this case, there could be data where a transition over a particular time interval is very unlikely given the model parameters.   But this might not be easy to detect. 

msm estimates the parameters of a model by using optimisation algorithms to find the maximum of the likelihood function for the parameters given the observed data.   Some of these algorithms can make use of the derivatives of the likelihood function (with respect to the parameters) if they are available, but can work in an alternative way if these derivatives are not available.  The `use.deriv` argument just selects between these two ways of working.  There is no way for a user to tell beforehand whether one optimisation algorithm will work better than another.

**Comment by poradamc** [comment]
Thank you, Prof. Jackson!
