### ISSUE TITLE
Derive transition probabilities analytically

### ISSUE THREAD

**Issue by snozhati** [chjackson/msm#7]
I would like to find Transition Probability Matrix (TPM) analytically from the generator matrix. It seems it does not work, it seems it computes TPM for t=1.
```
GG= matrix(c(-2,1,1,1,-2,1,1,1,-2),nrow=3,ncol=3,byrow = T)
MatrixExp(GG,method ="analytic")
```
It does not give me the analytical form based on exponential function, like Mathematica. Please take a look at the Mathematica example[ http://reference.wolfram.com/language/ref/ContinuousMarkovProcess.html](url).

**Comment by chjackson** [comment]
You have misunderstood what this is supposed to do.  It calculates the matrix exponential by using an analytic formula.  It is not supposed to present the analytic formula itself.  If you want to see the analytic expressions used, they are in the package source file https://github.com/chjackson/msm/blob/master/src/analyticp.c
