### ISSUE TITLE
Constraining transition rates to be equal

### ISSUE THREAD

**Issue by marc-vaisband** [chjackson/msm#70]
Dear Prof. Jackson,

the msm documentation contains instructions on how to specify that the effect of covariates should be equal on multiple transition rates. I would like to ask about a different case, where we want to constrain the "base transition rates" to be equal for several transitions.

Imagine a four state model, where we have transitions 1->2 (rate u), 1->3 (rate v), 2->4 (rate v), 3->4 (rate u), and where we want to estimate u and v. (I realise that in this trivial case, the estimation of u and v completely decouples, it's just a minimal example). 

Is it possible to include this constraint (namely that q12 = q34, and q13 = q24) into an msm model specification?

Thank you very much in advance

**Comment by chjackson** [comment]
For the benefit of other users finding this in a web search, this is `msm(...,qconstraint=)`, see `help(msm)`.
