### ISSUE TITLE
fixedpars to specify covariates with constraints

### ISSUE THREAD

**Issue by philophthalmus** [chjackson/msm#71]
Dear Prof. Jackson,

I am trying to set up an msm model in which a covariate, `age`  only affects certain transitions with a constraint that the absolute effect of `age` is identical for reverse transitions.
For example:
All transitions are plausible, such that
 `Q <- rbind(c(0, 1, 1, 1, 1),
           c(1, 0, 1, 1, 1),
           c(1, 1, 0, 1, 1),
           c(1, 1, 1, 0, 1),
           c(1, 1, 1, 1, 0))`

Yet, there is only sufficient data to estimate the effect of `age` on transitions involving states, `1` `3` and `4` 
 `
msm_age <- msm(outcomes ~ month,
                    subject = subject,
                    data = data, 
                    qmatrix = Q,
                    covariates = list("1-3" = ~ age,
                                      "1-4" = ~ age,
                                      "3-1" = ~ age,
                                      "3-4" = ~ age,
                                      "4-1" = ~ age,
                                      "4-3" = ~ age), 
                    gen.inits=TRUE)
`
On top of this, I would like also to constrain covariates such that `3-1` is `-1` of `1-3`, `4-1` is `-2` of `1-4` and so on.
In the manual, I found a potential solution where it states:
  
"A `fixedpars` statement can also be used for fixing covariate effect parameters to zero, that is
to assume no effect of a covariate on a certain transition rate."

Unfortunately, I am not sure how to take advantage of `fixedpars` without a further example, and I would be grateful if you could directly me towards an example code on this topic.

Thank you in advance,

**Comment by chjackson** [comment]
Do these course notes help?  

https://chjackson.github.io/msm/msmcourse/covariates.html#msm-syntax-covariates-on-rates-of-specific-transitions

https://chjackson.github.io/msm/msmcourse/covariates.html#identical-effects-of-same-covariate-on-different-transitions  

`fixedpars` isn't needed any more for this situation - that comment dated from a version before you could simply do [this](https://chjackson.github.io/msm/msmcourse/covariates.html#msm-syntax-covariates-on-rates-of-specific-transitions).
