### ISSUE TITLE
rtnorm runs forever for valid values

### ISSUE THREAD

**Issue by MLopez-Ibanez** [chjackson/msm#72]
```R
msm::rtnorm(1, .5, 0, 1, 2)
```

Perhaps sd ~ 0 should be handled instantaneously as a special case.

**Comment by MLopez-Ibanez** [comment]
```R
msm::rtnorm(1, .5, 2.220446e-160, 1 , 2)
```

I think `sd == 0` should use a tolerance, for example, `sd < .Machine$double.eps`

**Comment by chjackson** [comment]
Thanks - fixed.
