### ISSUE TITLE
Wall time restriction on optimization

### ISSUE THREAD

**Issue by marc-vaisband** [chjackson/msm#77]
Is it possible to pass an argument to optim which would limit the wall time taken by the optimization routine? The documentation contains parameters for the maximum number of _iterations_ which can be passed through to optim via the control argument, but does not seem to allow for a max time.

**Comment by chjackson** [comment]
`help(optim)` suggests not.  This functionality might exist for some other optimisation function out there, but I'm not aware of any.  

(It's not conceptually hard to use a new optimisation function in `msm` - though it's not thoroughly documented how to do this - basically you write a `msm.optim....` function that looks like one of the ones in [R/optim.R](https://github.com/chjackson/msm/blob/master/R/optim.R))

You could do a training run with a small number of iterations to estimate the time taken per iteration, then use that to determine `maxit`.
