### ISSUE TITLE
Question on MSM estimation with very few or no observations for a given transition

### ISSUE THREAD

**Issue by clarks7** [chjackson/msm#81]
Hi Dr. Jackson, 

Thank you so much for your excellent r package and extremely helpful course materials!

This may be a stupid question, but I'm working with very small sample (see state table of counts per transition attached). I know that the transition structure shouldn't be based on nonzero elements of this table, but I'm not understanding how the transition from 0 to 1, for example, would be estimated with 0 observations for this transition (i.e., what data would we use for constraining the 0 to 2 and 0 to 3 states to move through state 1?). 

Also, I'm assuming that any MSM fitted to this data will have to be very, very simple. Is there a rule of thumb for how many observations events per transition are needed for reliable estimation?

Thank you in advance for any feedback!

![MSM](https://github.com/chjackson/msm/assets/95888461/84c70e9c-f592-48b9-8904-d755b1b62ce5)

**Comment by chjackson** [comment]
In theory, suppose your model allows 0-1 and 1-2 transitions, but not 0-2.  Then if you have observed 1-2 data, that gives information on the 1-2 rate.  Then if you have 0-2 data, you can deduce information about the 0-1 rate, even if you don't have observations in 1.

But there's no easy one-to-one mapping between counts of transitions over an interval and transition intensities in continuous time, so there's no good rule of thumb.   Often you can only tell if a model is possible by trying to fit it.  Then if it converges and the confidence intervals are not very wide, checking that the results are realistic.  In your case, I doubt you'd be able to estimate any rates of transition out of state 0.

**Comment by clarks7** [comment]
Hi Dr. Jackson, 

This is really helpful and answers both of my questions!

Thank you for the very fast response and providing so much support for users of the package!
