### ISSUE TITLE
Question about maximum likelihood of msm

### ISSUE THREAD

**Issue by 26pan** [chjackson/msm#84]
Hi Prof. Jackson,
 Thank you for providing the msm package! When I run msm, he offers this warning"In msm(disease ~ time, subject = eid, data = data14, qmatrix = Q, Optimisation has probably not converged to the maximum likelihood - Hessian is not positive definite."

I've changed the number of follow-up days to years, trying to make it more modest, but it's not working. I have 130,000 individuals with 300,000 lines of data. The covariable is the air pollution number, and this is some code I use. I want to know what causes him not to act, and what else I can do about it.
![b70a366378a06891980f008d1b5ea13](https://github.com/chjackson/msm/assets/151415542/32f03264-4576-487a-9276-5582263053b7)
![c44bd3eaeebfa04b2126b02583a1c94](https://github.com/chjackson/msm/assets/151415542/16df54ae-d737-4678-9df0-ac3dae4f7f62)

Thank you very much!

**Comment by chjackson** [comment]
I'd start off by fitting the model without covariates.  If it converges, use the estimates to obtain initial values for larger models.   Then try one covariate at a time.   Are those three covariates highly correlated with each other?  I'd expect that for e.g. traffic-related air pollution.   That might cause problems with estimation.

**Comment by 26pan** [comment]
> chjackson

Thank you very much Professor chjackson for your reply. I followed your suggestion to fit the model without covariates first, but he still showed no fit, I was very confused about it.
I'm wondering if there's something wrong with the matrix Q setup or the data itself.
![1701749148699](https://github.com/chjackson/msm/assets/151415542/857e0afd-de36-4873-aaaa-2b892b43bf04)
![1701749163584](https://github.com/chjackson/msm/assets/151415542/bf734d91-f6d1-41c5-bda5-adbab08f1c6a)
![1701749182480](https://github.com/chjackson/msm/assets/151415542/00fab5ff-6ef5-4f95-8b3e-dfa0109d1cd8)

**Comment by chjackson** [comment]
Check the [observation scheme](https://chjackson.github.io/msm/msmcourse/msmbasic.html#obstype) - you have specified that the data are intermittently observed, and you don't know the transition times, but is that correct?  If you know the exact times of death (state 4 in your case), you should set `deathexact=4`.  

Also try some simple summaries of your data, e.g. using [`statetable.msm`](https://chjackson.github.io/msm/msmcourse/msmbasic.html#summarising-the-data), for the states.  And are there any extreme transition times?    There may be an outlying data point somewhere.  Fitting the model to smaller subsets of the data may help to identify this.

**Comment by 26pan** [comment]
> Fitting the model to smaller subsets of the data may help to identify this

Thank you!
