### ISSUE TITLE
multiple covariates

### ISSUE THREAD

**Issue by 26pan** [chjackson/msm#86]
Hi Prof. Jackson,
    Thank you very much for your patient response all the time. One of the questions I want to ask today is how to use the msm function to adjust a data set with multiple covariates. For example, gender, age, smoking status, race and other factors may cause some interference to the results, and they need to be covariated, such as part of the following article.
![1702283930844](https://github.com/chjackson/msm/assets/151415542/8e13ede4-93cc-44fb-9714-86b0cdbde9a5)
Thank you again for your kind help！

**Comment by 26pan** [comment]
The second question is do we need to delete subjects that are in state 1 from beginning to end?

**Comment by chjackson** [comment]
Is the answer to your question about covariates found in https://chjackson.github.io/msm/msmcourse/covariates.html ? How to build a regression model is a very broad statistical question, and not really specific to multi-state models. The only extra challenge with multi-state models is that you might want different covariates on different transition rates. 

Certainly do not delete people who remained in the same state, because they give you information about the rate of transition out of that state.

**Comment by 26pan** [comment]
> 您关于在 https://chjackson.github.io/msm/msmcourse/covariates.html 中找到协变量的问题的答案吗？如何构建回归模型是一个非常广泛的统计问题，并不是真正特定于多状态模型的。多状态模型的唯一额外挑战是，您可能希望在不同的转换率上使用不同的协变量。
> 
> 当然，不要删除保持相同状态的人，因为他们会为您提供有关从该状态过渡的速率的信息。

Do you mean to build regression models before using msm functions?

**Comment by chjackson** [comment]
"Regression model" means any model that links covariates to an outcome. In the context of a multi-state model, a regression model is the log-linear model that links covariates to the transition intensity.  By "building" the model, I mean choosing which covariates are included.

**Comment by chjackson** [comment]
The msm software makes no distinction between a predictor of interest and other predictors you need to adjust for.  Most regression modelling software doesn't make this distinction either.  I agree that in some contexts the word "covariate" is used to mean predictors other than one particular predictor of interest (e.g. in randomised trials of treatments).  But generally "covariate" can mean any predictor (https://en.wikipedia.org/wiki/Dependent_and_independent_variables#Statistics_synonyms).

**Comment by 26pan** [comment]
> The msm software makes no distinction between a predictor of interest and other predictors you need to adjust for. Most regression modelling software doesn't make this distinction either. I agree that in some contexts the word "covariate" is used to mean predictors other than one particular predictor of interest (e.g. in randomised trials of treatments). But generally "covariate" can mean any predictor (https://en.wikipedia.org/wiki/Dependent_and_independent_variables#Statistics_synonyms).

Thank you Prof. Jackson!
