### ISSUE TITLE
Expose likelihood function

### ISSUE THREAD

**Issue by MikeLydeamore** [chjackson/msm#9]
Currently the only way to obtain the likelihood is through the use of logLik.msm, which only extracts the maximum value.
Would it be possible to add a way to calculate the likelihood for a given set of parameters and a given set of data?

**Comment by chjackson** [comment]
``msm(..., fixedpars=TRUE)`` returns the likelihood at the initial values given the supplied data, instead of doing optimisation.

**Comment by MikeLydeamore** [comment]
Perfect. Missed that one.
