### ISSUE TITLE
Error in estimating transition intensities 

### ISSUE THREAD

**Issue by jiali3wang** [chjackson/msm#90]
Dear Dr. Jackson, 
Thank you for your effort to build the package! 
I have a question about estimating the transition intensities in the Q matrix. First of all, I tried to use the build-in function "sim.msm" to generate one realisation from a continuous-time Markov process by specifying true intensities, and then the main function "msm" to recover the intensities. However, I got estimates that were away from the no value, by using different options for starting values, either with (maxtime=4) or without censoring (maxtime=999). Please see my sample code below. 

Could you please give me some clue? Thank you so much for your help!

```
 # true transition intensities in Q matrix
qmatrix <- rbind(
  c(-0.2, 0.1, 0.1 ),
  c(0, -0.6, 0.6 ),
  c(0, 0, 0)
) 

set.seed(1)

 # simulate data for 5000 patients 
dat <-NULL
for (i in 1:5000){
  sim <-sim.msm(qmatrix, maxtime=9999) 
  sim.dat <- data.frame(id=i, state=sim$states, time=sim$times)
  dat <-rbind(dat, sim.dat)
}

statetable.msm(state, id, data=dat)

Q.crude <- crudeinits.msm(state ~ time, id, data=dat,
                          qmatrix=qmatrix)  
Q.crude  ## this is close to the true values

dat.msm <- msm( state ~ time, subject= id, data = dat,
                qmatrix = Q.crude, deathexact = 3)
dat.msm ## this is far away from the true values

```

**Comment by chjackson** [comment]
Try adding `exacttimes=TRUE` to the call to `msm`.  The function `sim.msm` simulates times of transition, so if you want to treat these as known times when fitting the model, you need to tell `msm` this, via the `obstype` or `exacttimes` arguments.  By default, `msm` treats the data as intermittently observed states.
