### ISSUE TITLE
Censored states in simfitted.msm

### ISSUE THREAD

**Issue by pkirwan** [chjackson/msm#91]
When using `simfitted.msm` to simulate panel data from a fitted msm model with censored states, none of the states are censored in the dataset returned.

I think this bug is caused by `simfitted.msm` encoding censored states from the model in an indicator column named `"(cens)"`, whereas `simmulti.msm` expects this column to be named `"cens"`.

A simple fix would be updating [this line](https://github.com/chjackson/msm/blob/6d26a8f77d8e202d112fba2b6d81e7b44f86a9fd/R/simul.R#L542C5-L542C214):
`sim.df$"(cens)" <- ifelse(sim.df$"(state)" %in% 1:x$qmodel$nstates, 0, sim.df$"(state)")` 
to
`sim.df$"cens" <- ifelse(sim.df$"(state)" %in% 1:x$qmodel$nstates, 0, sim.df$"(state)")`

**Comment by chjackson** [comment]
Thanks for the report, Peter.  Now fixed in https://github.com/chjackson/msm/commit/a29de0b018aa8f653076fc768c6eb24146329f97
