### ISSUE TITLE
Fitting simple healthy-ill-death model without recovery

### ISSUE THREAD

**Issue by taledv** [chjackson/msm#93]
Hi again Dr. Jackson,
Thanks a lot for the help so far, I've solved all the issues I have with total times.
Now I encounter a new one, fitting a very simple model without recovery.

This code snippest works:
q <- 0.001
Q <- rbind(c(0,q,q), c(q,0,q),c(0,0,0))
model_without <- msm(state ~ time, subject=id, data = df_state_without, qmatrix=Q, gen.inits=TRUE, covariates=~age, 
                     center=TRUE, control=list(reltol=1e-6, maxit=1000, fnscale=10000), method="BFGS", deathexact = 3, censor=9)

where df_state_without is removing all people that has recovery (2,1).
Notices that Q allows recovery (2,1) value is not 0.
But this code:
q <- 0.001
Q <- rbind(c(0,q,q), c(0,0,q),c(0,0,0))
model_without <- msm(state ~ time, subject=id, data = df_state_without, qmatrix=Q, gen.inits=TRUE, covariates=~age, 
                     center=TRUE, control=list(reltol=1e-6, maxit=1000, fnscale=10000), method="BFGS", deathexact = 3, censor=9)
The only change is inserting zero in the (2,1) position in Q, give the error that it attached:
![image](https://github.com/chjackson/msm/assets/73901790/28e34127-6cf4-43b6-b4a2-b366d37f58cc)

I can't seem to figure out why, because when I fit with recovery, it of-course finds coefficients very low for the q12 value, since I removed all data with recovery, seen below: (-8 bias and almost 0 for age, thus q12=exp(-8)=0).
![image](https://github.com/chjackson/msm/assets/73901790/452b7185-8a4c-4f9d-8927-f4d093deba3d)

When I use the full data (with the people that had recovery) I get the following coefficient table:
![image](https://github.com/chjackson/msm/assets/73901790/8fec9402-6ee1-4d01-ad90-c0b0c9a4d117)
You can see that now beta21_intercept is -1.95 and not -8, meaning it did fit well the recovery.

I wonder what happens when you try to put q21=0 when you do have recoveries, do you just ignore those in the log-likelihood?
Anyway, with or without recoveries in the data, I'm not able to fit a non-recovery model. 
I removed on purpose those people with recoveries just to see if now it works, without success.
I tried playing with the control parameters, also without success.
As I've read in your manual, inserting zero in Q means "don't learn this transition rate", but I can't make it work.

Thank's again in advance,
Tal.

**Comment by chjackson** [comment]
The `optim` error you have found means that the data are incompatible with the model (as defined by the model structure and initial values), hence the likelihood is zero, or the minus log likelihood is `-Inf`.

You could debug this by calling `msm(..., fixedpars=TRUE)` which simply evaluates the likelihood at the starting values.  You will get a result of `-Inf`, but if you repeat this with subsets of the data (e.g. one subject at a time) you may discover which subsets give a finite log-likelihood, and which give an infinite log-likelihood.  Hence you can identify which parts of the data are not compatible with the model.

If there is recovery in the data, but the model does not allow for this, then there should be an error message, something like "Data may be inconsistent with transition matrix".

**Comment by taledv** [comment]
Thank you, I will try this. As you said it gives Inf. But what can be wrong with the data? Can you give an example? It seems weird as it is only id, age, time, and state.

Regarding the recovery, so it will give just a warning if I insert 0 at q21 if such a transition exists in the data, it will not crush? will it be able to fit? you just ignore all p21's in the log-likelihood? (because beta21's don't exist).
Thus I should be able (assuming i find what wrong with the data) to "tell" the model to not fit beta_21 meaning q21=0, even if such transitions occur in the data?

**Comment by chjackson** [comment]
No, this will give an error message and not fit the model.  It doesn't understand what you mean if you try to fit a model under which the data are impossible.

I can't tell what is going on without seeing the data, but if you can narrow it down to a single observation or subject that reproduces the problem I might be able to tell.

**Comment by taledv** [comment]
Yes but now it doesn't even get to there, it fails at the beginning (initialization), I will try to run subject by subject and see, hopefully the model can be fitted with so little data (single person with a few observations). But good to know, that even if I find the problem with the data, I can't fit a non-recovery model using data that has recoveries.
Thanks!

**Comment by taledv** [comment]
Maybe there is a problem with people that are only healthy? meaning they have only state = 1? (or any other single state)?

**Comment by chjackson** [comment]
You don't need to fit the model to identify the problem - just to evaluate the likelihood at the initial values.  You can do this with a small amount of data.   

You cannot fit a non-recovery model using data with recoveries.    You would have to exclude recoveries from the data beforehand.    Please try to read my replies more carefully!

**Comment by taledv** [comment]
Yes I got that, sorry if I wasn't clear. So basically if I use fixedpars=TRUE the model is not fitted? Did you see my other idea above? that maybe the problem is people that stay healthy across all their observations? 
It gave the following error when tried with fixedpars=TRUE, only the subject:
![image](https://github.com/chjackson/msm/assets/73901790/2a23aa9c-d022-4d87-bd00-7e508837a754)
Error:
![image](https://github.com/chjackson/msm/assets/73901790/7ecb138d-6ee9-48f6-bbad-0dcff29f2cae)
It stopped the loop over all subjects after this.

**Comment by chjackson** [comment]
`gen.inits=TRUE` is inappropriate here.   You are trying to work out why your original model and initial values gave a zero likelihood.   When you set `gen.inits=TRUE` you are obtaining the initial values from a crude summary of the data - and in this case there are no transitions in the data, so the initial values for the transition intensities will all be zero.  Use whatever initial values were being used originally - these can be recreated using the function `crudeinits.msm()`.

**Comment by taledv** [comment]
As you suggested, I tried to discover the Q matrix using crudeinits.msm(), it gave the following error that the time is not ordered, even though it is ordered:
![image](https://github.com/chjackson/msm/assets/73901790/36a8a436-4703-4b1d-b2ef-4c15aa1ae620)
I thought to get this initalization for Q, and use it in the above loop with gen.inits=False, as you said.

**Comment by taledv** [comment]
BTW, even if I set q21=0, and I have transitions between 2 and 1 in the data, this should be fine as long as there is a way to get from state 2 to 1 (of-course not directly because q21=0 but if from 2 to 3 and from 3 to 1 was available, meaning q23,q31>0 this would be fine, right). What I mean is, it is not allowed ONLY if p21 is also 0 (than log(0) = -inf in the loglikelihood).

**Comment by chjackson** [comment]
You missed out the `subject` argument to `crudeinits.msm`.

**Comment by taledv** [comment]
You are right, it works. I already used some made up Q matrix, and it still keeps running, but I may use this one instead:
![image](https://github.com/chjackson/msm/assets/73901790/cd92289c-eba7-40a9-98cc-e2eabeee4b41)
As you see, q21 is very very small (expected as there are not recoveries in the data)
